index.html, script.js, style.css
#1 Added API call to display day based weather for the city in focus 
Html and CSS file modified for styling purpose
Added Moment.js for extension purpose
If any questions or changes needed let me know
=> Week based weather update

index.html, script.js, style.css
=> Added Sunrise and Sunset time.

CODE_OF_CONDUCT.md, CONTRIBUTING.md
I have added the code of conduct file and contribution guidelines file. thanks for giving me this opportunity
=> added code of conduct

style.css
=> Responsive Weekly Report

script.js, style.css
Full Date is now displayed #14
=> add full date

script.js
Uses the browser location feature to detect user location to show data.
=> Added location based infos

script.js
Reverts avinash201199/weather-app#17
=> Revert "Added location based infos"

style.css
Added focus styles to the search input and button for better accessibility.
=> Added form focus states for improved accessibility

style.css
fix to the background image repeating and more responsive
=> fix to the background image repeating and more responsive

index.html, style.css
Hi! In this PR I'm adding the following changes:
- meta description
- adding aria-label to a search button [gives it accessible name]
- adding autocomplete attribute to input field [city]
- adding styles for input field and search button (matches colour contrast required by WCAG 2.2 guidelines)
- replacing a` <div>` with a `<main>` and keeping its original styles
- updating the order of headings and keeping their original font sizes
=> UI suggestions by matea

index.html, script.js, style.css
Air Quality Index with description.
=> Added Air Quality

index.html, style.css
Although I made it a bit interactive by hover functions but still I am not able to make a detailed display of the future forecast due to some html tag things. 
In the html, I have added view-more class which is intended to give a detailed display but whenever it is getting on browser, the edited html code went missing. Adding it again and again by inspect option helped me a bit to shape it properly.
Also please let me know if there were any changes to be made in the contribution I have done.
=> Interactive Future Forecast

assets/css/style.css
- Added padding to make the tiles visually appealing
- Added hover effect with grey colour and white border
=> Added hover effect to the .weather-forecast-item

assets/js/Capitals.js, assets/js/script.js, index.html
If we type a country name, it will show the capital's weather. #HacktoberFest @avinash201199
=> Country Search

assets/css/style.css
Added Responsive for more Devices of more width than 1200px and add a smooth transition to the background of the card.
=> Added Responsive for more Device and add smooth transition

assets/js/script.js
At the beginning try to get current location weather, if it's not possible it will get Delhi weather. 
[gif](https://media.giphy.com/media/al75X18L7MsudcwcJ8/giphy.gif) show fix #51
=> weather by current location

assets/js/script.js
Reverts avinash201199/weather-app#52
=> Revert "weather by current location"

assets/css/style.css, assets/js/script.js, index.html
Some small parts of UI improved,
=> some text and code added

assets/css/style.css, assets/js/script.js, index.html
Reverts avinash201199/weather-app#55
=> Revert "some text and code added"

assets/css/style.css
added a new search animation hope you like it
=> new search text animation

assets/css/style.css, assets/js/script.js, index.html
The UI is improved and the function formatAMPM in script.js is changed with one line of code for better view produces the same output.
=> Fixed some UI and improved the function formatAMPM

assets/css/style.css, index.html
=> UX enhancements - Improved the main weather card

assets/css/style.css, index.html
The search bar is now in the center.
=> centered the search bar and search icon

index.html
Reverts avinash201199/weather-app#84
=> Revert "Added main element to give screen readers a landmark region"

assets/css/style.css, assets/js/script.js, index.html
change the font style of various text likewise adding a glassmorphic effect on hover on the forecast card
=> updated font styles and forecast card look

index.html
Issue #88 
Added alt attributes for better SEO 
This would improve the accessibility of the site
=> added alt text to all images

index.html
Reverts avinash201199/weather-app#93
=> Revert "added alt text to all images"

assets/js/script.js
Reverts avinash201199/weather-app#92
=> Revert "load user city's weather when they visit"

index.html
I have added the links to the basic weather terminologies so that the people who are not aware of these terms will get beneffited.
=> To Know the Basic Weather Terminology.

assets/css/style.css, index.html
=> added width and height to imgs

assets/js/script.js, index.html
Reverts avinash201199/weather-app#125
=> Revert "added alt to images"

lang/translation.js
I add the spanish languaje into the traslation.js file
=> Adding the spanish languaje

index.html
Present Day and Time added to avoid confusion that how far the app is predicting.
=> Day of Week and Timeline added

assets/css/style.css
**Previous Main weather card**
**New main weather card**
=> Updation in main weather card (issue #68)

assets/js/script.js, lang/translation.js
- support `en` and also `en-US` translations (both are valid)
- fix header background if title has 2 lines or more (= unlimited height)
- add german translation
- used the `day` and `night` translation keys on the weather items (was hardcoded to `DAY` and `NIGHT`)
=> Support language-based translations and add german translation

index.html
Added a background to the date displayed at the top of the page. Makes it visible across different backgrounds.
Fixes #147
=> Make date at top of page more readable

.Github/FUNDING.yaml
Feel free to make page and update link si, people can donate this project via sponsorship
=> dx: added sponsor link

assets/css/style.css, assets/js/script.js, index.html
Hi Avinash,
I have made some changes to the UI and added better font styling to the website.
Here is the preview:
=> Made some changes to the UI and added better font styling to the website, Issue No : #157

assets/css/style.css, index.html
Hi @avinash201199 
Made the changes to fix the issue of temperature toggle overlap with  search bar on responsive layout
Can you please review the PR
Issue Link:- https://github.com/avinash201199/weather-app/issues/158
Screencast for the change
https://www.loom.com/share/4bca273405b649229ffe10abd4f86808
=> Fix temperature checkbox overlap issue

assets/css/style.css, index.html
Changes in footer styling along with its height.
=> changes in footer style , issue no: 161

assets/css/style.css, index.html
Improved the styling of Temperature Unit Converter Button and the icons in footer, both in responsive mode.
=> Temp Unit Button and links in footer

assets/js/script.js, index.html
Hi Avinash,
Raised PR for issue no: # 168
Kindly approve my PR.
Adding screenshot for your reference.
=> Live clock feature -> Bug fix for issue no: 168 - Improved the Date,Time from static to Dynamic using SetInterval- Changes time for every one second

assets/css/style.css, index.html
Issue no:- #174 
Fixed social media icons for every screen possible & also fixed the GitHub icon image which was not visible due to the black background but now it's fixed.
=> Fixed social media icons

assets/js/script.js
=> toggle bug fixed

.Github/ISSUE_TEMPLATE/features.yaml, .Github/PULL_REQUEST_TEMPLATE.md
Now contributors will have a template to add features in app will speed up adding new features
=> dx: added features template 

lang/translation.js
=> Update translation.js adding french language

index.html
Toggle has been updated so it shows the currently selected temperature unit
=> fix temp toggle ux

assets/css/style.css, index.html
Added and refined the social media icons hover effect, for hacktoberfest
=> hover effect

lang/translation.js
Closes open issue by myself (adding translation in Bahasa Indonesia) #199
- lang/translation.js
=> Closes #199

CONTRIBUTING.md
`Closes #202`
Fixed grammar mistakes in CONTRIBUTING.md
=> Fixed grammar mistakes in CONTRIBUTING.md

lang/translation.js
-
This PR adds the greek language on Weather App
I also plan adding japanese localization. (Added)
-
=> Add Greek , Japanese Localization

index.html
=> UI enhancement

lang/translation.js
-
This PR adds albanian language on Weather App
-
-
=> Add Albanian Localization

assets/css/style.css, index.html
I have improved the UI of the footer. Please consider my work and merge it under issue #211 under Hacktoberfest'2k22
Thank You
=> Improving footer UI

CONTRIBUTING.md
=> Corrected grammar in CONTRIBUTING.MD

assets/css/style.css
i have found in your demo that when you hover footer links its width increases but in ux this is not good
so i used smooth property which is  transform scale 
<ol>
<li>decrease transition duration</li>
</ol>
=> updated footer links

index.html
=> Temperature Toggle button attribute bug fix (issue no-224)

index.html
=> I have increased the border-radius of the search card making it look more attractive.

index.html
=> Added alternative text in all image tags

assets/css/style.css
Reverts avinash201199/weather-app#232
=> Revert "Update style.css"

assets/css/style.css, assets/js/script.js, index.html, lang/translation.js
Updated `script.js`, `style.css`, `lang/translation.js`, and `index.html` file.
At present, method involves utilizing an API to retrieve air quality index (AQI) data based on latitude and longitude coordinates. However, I have encountered discrepancies in location data when obtaining latitude and longitude information through the OpenWeather service, particularly for certain cities. This pull request addresses this issue by proposing a shift in our AQI API usage, switching to a search API and incorporating the city name as a keyword. Additionally, I have also introduced a new label, 'Not Available,' translated into multiple languages, to indicate instances where the Air Quality Index data is unavailable for numerous locations. I've also implemented a color-coding system for the air …
=> Change AQI api and add AQI color index

assets/css/style.css, assets/js/script.js, index.html
Closes #236 
- Added WhatsApp icon to the top left corner of the screen via the html file. 
- Added corresponding event listener in the js file to open Whatsapp in a new tab.
- Added code to create the message to be shared.
=> Enabling WhatsApp sharing

assets/css/style.css
- Closes #242  
- Weather report which flowed out of the screen due to staying issues has been fixed
=> Small screen overflow issue fixed

assets/css/style.css
Closes #246
Changes made in assets/CSS/style.css
=> Whatsapp icon fixed

assets/css/style.css, index.html
`Closes #249 `
I have fixed the position of the whatsapp icon, now it is not moving when page is scrolled up/down.
=> Whatsapp icon fixed 

assets/js/script.js
Closes #251
Please add the Hacktoberfest label
=> Fixed whatsapp issue

assets/css/style.css
I have added some CSS to fix the issue
The WhatsApp button was not visible for mobile viewport
I have added some CSS to fix the mentioned issue.
=> Fixed WhatsApp button visibility in mobile viewport

assets/css/style.css, assets/js/script.js, index.html
=> added mouse follower 

assets/js/script.js, index.html
Closes #271 
Added whatsapp-button id to properly target it.
=> fix: added functionality to WhatsApp button

assets/js/script.js
=>  Add clearTimeout and null checks 

.gitignore, assets/compiled-css/styles.css, assets/css/styles.css, gulpfile.js, index.html, package-lock.json, package.json, sass/styles.scss
Features:
**1. Live Server feature 
2. Auto reload of browser upon changes in `.css & .html` files.
3. SASS support for our project.**
As i mentioned in the issues, gulp has lot of advantages, successfully integrated gulp to our weather app project. 
Video has been uploaded in my drive for your understanding, and for step by step understanding with screenshots i have added in the guide docx below. 
[Gulp_explantion_video](https://drive.google.com/file/d/1EBboAIqGMNPFxubkib6wpvlq_PQTSe-n/view?usp=drive_link)
[Gulp_installation_guide](https://docs.google.com/document/d/1nd4ZIWGeYi4k9cvX4f67iSlhLoJPc3rV/edit?usp=drive_link&ouid=112285357584959964547&rtpof=true&sd=true)
For gulpfile.js file, we can use the file as it. of course if we want to customize it we can do.
**Steps:**
step 1: `git …
=> [feat]: Gulp integration to weather app

assets/css/style.css
=> I changed the colour of mic and search icon to black.

assets/css/style.css, index.html
[#301](https://github.com/avinash201199/weather-app/issues/301)
This PR contains the Twitter/X icon in the Footer.
**Note**: We need to change the redirection url, once @avinash201199 Will provide the Twitter URL, then we will add the same.
=> Added: Twitter/X icon added

assets/js/script.js
@avinash201199 can you review it and merge the pr
=> city error functionality done issue no.  #255

assets/css/style.css, assets/js/script.js, index.html
- Restructured the style.css file which was a little disorganized
- Introduced better stylic that looks more aesthetic than the previous one
- Changed the font style
=> Styling Changes

assets/css/style.css, assets/js/script.js, index.html
Reverts avinash201199/weather-app#309
=> Revert "Styling Changes"

assets/css/style.css, index.html
Issue #313 - **Stylize the cards showing the temperature for the week,** resolved.
Added a glassphormism effect on the cards and also positioned them.
The changes are done in two files index.html and style.css
=> restyled temperature cards

assets/css/style.css, assets/js/script.js
Closes #322 
Added leading zeros to time format in header and fomatAMPM function
NA
=> fix: Time format with leading zeros

.vscode/settings.json, assets/css/styles.css, assets/js/script.js, index.html
Issue #336 
Hey mod @avinash201199 , I put in some real work and finally got done with fixing all the design inconsistencies and making the overall design aesthetic and modern. I am attaching some screenshots and video as well. 
https://github.com/user-attachments/assets/d79f7eaf-5329-4771-a499-210567c09fb7
I hope you liked the new design. All the functionalities are still intact and the site is even more responsive than before. Overll, I am very happy with the results. Hope you merge this :)
=> Redesigned the entire frontend to better fit modern design standards

assets/css/style.css
Reverts avinash201199/weather-app#341
=> Revert "Whatsapp_hover_effect"

assets/js/script.js
#326 
#326 here 326 issue stand for fetch auto location feature in app 
➕ Changes Introduced
Added coded  in script.js file to added location using gps through lat,lon 
now it has feature to auto fetch location,updated the get locaion function for better accuracy
=> feat: add auto-location feature to weather app
